[tool.commitizen]
version = "0.2.0a0"
version_files = ["src/noosphere/__version__.py", "pyproject.toml"]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version â†’ $new_version [skip-ci]"
